const express = require("express");
const router = express.Router();
const receiptRouter = require("./receipts.js");

router.use("/receipts", receiptRouter);

router.get("/test", (req, res) => {
  return res.status(200).json({ message: "Test Route" });
});

router.get("/", (req, res) => {
  const apiEndpoints = {
    "Process Receipts": {
      path: "/receipts/process",
      method: "POST",
      payload: "Receipt JSON",
      response: "JSON containing an id for the receipt",
      description:
        "Takes in a JSON receipt and returns a JSON object with an ID generated by your code. The ID returned is the ID that should be passed into `/receipts/{id}/points` to get the number of points the receipt was awarded.",
      exampleRequest: {
        retailer: "Target",
        purchaseDate: "2022-01-01",
        purchaseTime: "13:01",
        items: [
          {
            shortDescription: "Mountain Dew 12PK",
            price: "6.49",
          },
          {
            shortDescription: "Emils Cheese Pizza",
            price: "12.25",
          },
          {
            shortDescription: "Knorr Creamy Chicken",
            price: "1.26",
          },
          {
            shortDescription: "Doritos Nacho Cheese",
            price: "3.35",
          },
          {
            shortDescription: "   Klarbrunn 12-PK 12 FL OZ  ",
            price: "12.00",
          },
        ],
        total: "35.35",
      },
      exampleResponse: {
        id: "7fb1377b-b223-49d9-a31a-5a02701dd310",
      },
    },
    "Get Points": {
      path: "/receipts/{id}/points",
      method: "GET",
      response: "A JSON object containing the number of points awarded",
      description:
        "A simple Getter endpoint that looks up the receipt by the ID and returns an object specifying the points awarded. How many points should be earned are defined by the rules below...",
      exampleResponse: {
        points: 32,
      },
    },
  };

  return res.status(200).json({
    message: "Welcome to the Receipt Processor API",
    developer: "Johnny Avila",
    endpoints: apiEndpoints,
  });
});

router.get("*", (req, res) => {
  return res.redirect("/");
});

module.exports = router;
